### ISSUE TITLE
Locally see branches

### ISSUE THREAD

**Issue by marcosmarp** [marcosmarp/signIn-signUp#10]
Just finished reading the documentation you leaved me in [this](https://github.com/marcosmarp/signIn-signUp/issues/3#issuecomment-894684791) comment, and there's one thing i didn't quite cached.

I understand the concept of working locally in my machine, commit the changes to the repository and then "push" them to the server. But, working with branches, how do i work specifically in one branch? What if i want to edit the code just in one branch, and still keep the main branch code locally? Is there a way to open the IDE through git bash? Or is there a concept i misunderstood?

From what i understood from the documentation, when you commit the changes, you are commiting them to the branch you're working on in the console. But, the main branch files or a different branch files, where are them?

To give an example, my local folder for the repo now have a .gitignore file, but i didn't merged the new branch with the main branch, so, that file should be there? Thanks!

**Comment by nahueespinosa** [comment]
Good question, let me try to explain:

Git state is stored locally in a hidden folder called `.git` inside your repo's folder. When you switch branches, git literally updates all related files inside that folder. As a result, all the applications on your computer can only see the current version of those files. Does that makes sense?

You can change your current branch in bash or in a GUI app and that will reflect everywhere else. Want it or not, you are always working on a branch with git (by default `main` or `master`) and the `checkout` command allows you to jump between branches.

One important remark to make here, is that git only cares about the files it's tracking. If you have untracked files, those will not be deleted when you jump between branches as they don't belong to any branch until you start tracking them (using the `add` command and `commit`).

So, regarding `.gitignore` you'd need to check two things:
- Is that file being tracked by git? (has it been added to a branch?)
- Are you still on the branch that added that file?

**Comment by marcosmarp** [comment]
Just checked! I switched branchs to the main in the Git Bash and the .gitignore file wasn't there anymore. Thanks for the answer!

I read about worktrees [here](https://opensource.com/article/21/4/git-worktree#:~:text=A%20Git%20worktree%20is%20a,and%20on%20a%20different%20branch.). What do you think? If i didn't misunderstood, this way you have each branch in a different folder, or the purpose of this "worktrees" are different?

**Comment by nahueespinosa** [comment]
Yes, exactly, they are useful if you need to work on two branches at the same time. But you could certainly live without them, so I wouldn't focus on them too much for now. Let's try to learn the basics first.

**Comment by marcosmarp** [comment]
Got it. Closing the issue. Thanks!
