### ISSUE TITLE
Different repo

### ISSUE THREAD

**Issue by marcosmarp** [marcosmarp/signIn-signUp#11]
Hey, i wanted to ask if it would be too much trouble to ask you for a little insight in another small project i'm working on. I feel like i'm in a dead end there and i can't seem to find the right answers online.

I totally understand if you can't or don't want to, just let me know if i'm being a PITA xD

Thanks!

**Comment by nahueespinosa** [comment]
Sure thing. Ask away!

**Comment by marcosmarp** [comment]
Will add you to the new repo and ask there! Thanks :)
