### ISSUE TITLE
Header organization

### ISSUE THREAD

**Issue by nahueespinosa** [marcosmarp/signIn-signUp#12]
## Description
Let's work on your header files! There are a couple things to address:

- Don't use a `common.h` header. The reason being that usually in software development you want to reduce [coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)) between modules. Each file should only include what it needs and nothing else.

- Don't define functions in header files. Those should be in a separate `.cpp` file.

- Use [header guards](https://www.learncpp.com/cpp-tutorial/header-guards/). Prefer the use of `#pragma once` over `#ifndef`.

## Definition of done
For now, let's take a step back and have only one `main.h` file and one `main.cpp`. And, once we change the code to use a `C++` approach instead of `C`, we can think of the different software modules we are using and how to split them into files.

Please, read the provided reference and make a decision on what to include in `main.h`. We can discuss the contents in the PR.

## References
https://docs.microsoft.com/en-us/cpp/cpp/header-files-cpp

**Comment by marcosmarp** [comment]
Got it! Just finished reading. Should i create the branch and PR once we merge #7?

**Comment by nahueespinosa** [comment]
> 
> 
> Got it! Just finished reading. Should i create the branch and PR once we merge #7?

Yeah, merge that PR, checkout to main, pull the latest changes and start working from there.
