### ISSUE TITLE
Container usage

### ISSUE THREAD

**Issue by nahueespinosa** [marcosmarp/signIn-signUp#16]
## Description
Good job using `std::vector` as container instead of an old array. Now let's harness all its power haha.

## Definition of done
- Use **range-for** when appropiate to iterate over all elements of your container.
- Remove the `amount_of_registered_users` global variable and instead use the `size()` method of the vector if you need the size.
- In `RegisterNewUser` functions, create a temp `UserData` variable and add it to the vector as the last step. Get rid of `registered_users_data[amount_of_registered_users-1]`.
- Investigate the difference between vector size and capacity. Remove all calls to `resize`.

## References
https://en.cppreference.com/w/cpp/container/vector
https://www.learncpp.com/cpp-tutorial/an-introduction-to-stdvector/

**Comment by marcosmarp** [comment]
Just finished reading the biblography you gave me :) 
> Investigate the difference between vector size and capacity.

I think i got the difference between size and capacity, being one the amount of elements in the vector and the other one the maximum posible size of the array before it has to be reallocated in memory. Should I be aware in the code of the reallocations of the vector and therefore his capacity? Or only the size of it truly matters in a high level end? Thanks!

> Remove all calls to resize.

I would say that `std::vector::push_back()` looks cleaner, do you agree? (just in case, it does indeed adds a new position to the vector, right?)

**Comment by nahueespinosa** [comment]
Right, unless you want to optimize certain things (which you shouldn't at this point), you don't really care about capacity. The vector can manage that internally.

Yes, `push_back()` is the way to go! The vector will allocate new memory if it exceeds its current capacity, but you don't have to think about it.

**Comment by marcosmarp** [comment]
Got it! Will start working on it. See ya in the PR xD
