### ISSUE TITLE
Using lambda functions

### ISSUE THREAD

**Issue by marcosmarp** [marcosmarp/signIn-signUp#20]
Hey, i've been reading about lambda functions and the <functional> library, but i found like 5 different ways of doing this, and still i don't quite catch the concept of what i'm supposed to do.

Correct me if i'm wrong, please:
Lambda functions are a type of functions that have the hability of using variables or parameters from the enviroment where they're declared, so you don't have to "pass" the argument to the function itself, it can take it from the sorroundings.
The idea of this is to "store" the body of the function in the class, and then, when called, the function will take the parameters (in our case the data vector).

Now, I'm loss in how to do this. I kind of drafted an idea of something, but I think i'm doing something else (functions pointers). Have a look:
```
struct Item {
    std::string name;
    int call_code;
    std::function<void(std::vector<UserData>&)> assigned_function;

    Item(const std::string received_name, int received_call_code, void (*received_function)(std::vector<UserData>&)) {
      name = received_name;
      call_code = received_call_code;
      assigned_function = received_function;
    }

    friend std::ostream& operator<<(std::ostream& os, const Item& item);
};
```
Tell me what you think! Thanks.

**Comment by nahueespinosa** [comment]
Yeah, I understand the confusion, first you should handle function pointers and later you can see if it's worth using lambdas or not. Now that I see the code, there are a couple of things that are worth focusing on before going into this. You were on the right path though. 

For now, I would refactor the code to make functions cleaner. Some hints:
- Assign a short and clear list of reponsibilities to each function. If a function has too many things going on (i.e. `RegisterNewUser`), break it down into pieces.
- Separate the logic of your code from the user input. I'm sorry I can't give you examples right now, but you shouldn't be printing to the console every other line, nor waiting for user input.
- Try using return values to know what to print after processing the data, and function parameters to pass around the user input.
- Look at the video I sent you the other day! And if you have time, I'm sure you can find this somewhere for a good read 😉 https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882
