### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by nahueespinosa** [marcosmarp/signIn-signUp#3]
## Description
It's very common to exclude files you usually don't need to track from your git repository. Some examples are machine generated files and executables.

The way to do this is with a `.gitignore` configuration file that contains a list of files to ignore.
Please, add one to your project that excludes:

- All files ending with `.o`
- The final executable of your project (`LogInDataBase`)

Reminder: Feel free to ask any questions.

## References
https://swcarpentry.github.io/git-novice-es/06-ignore/
https://www.atlassian.com/git/tutorials/saving-changes/gitignore
https://git-scm.com/docs/gitignore

**Comment by marcosmarp** [comment]
Should be done by now, had a hard time using Git Bash but I think I'm getting the hang of it. 
Some things didn't exactly matched with the [tutorial](https://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/) you gave me so just in case I attached a screenshot of the procedure so you can check it.

Btw: accidentally closed the PR, I managed to reopen it. Sorry!

![image](https://user-images.githubusercontent.com/88422056/128590803-1be32391-6480-49ad-afb5-4bcca77ba19f.png)
![image](https://user-images.githubusercontent.com/88422056/128590836-218975c4-3d9c-4152-a3d4-eea14b39ff32.png)

**Comment by nahueespinosa** [comment]
Oh no, sorry about that. That tutorial wasn't great.
I was hoping you stumble upon this line:
> The . indicates that all files will be untracked. You can untrack a specific file with git rm --cached foo.txt (thanks @amadeann).

And just remove file by file.

Git is not really user friendly, and understanding what's happening under the hood can really make a difference when deciding which commands to run.

I don't think running `git init` on an already initialized repository is a great idea. I'd suggest you delete your local copy of the repo (all relevant changes should already be on github) and create a new branch using this procedure:

```bash
$ git clone https://github.com/marcosmarp/signIn-signUp.git
$ git checkout main   # Checkout to main just in case
$ git pull            # I don't think we've discussed this but after merging a branch on github, you need to bring those changes to your local repository
$ git checkout -b marcos/gitignore   # Create branch from main and checkout to that branch
$ git add .gitignore
$ git commit -m "Create .gitignore"
$ git rm --cached *.o       # Untrack files ending in .o (repeat this for every file you wish to untrack)
$ git commit -m "Remove tracked files"
$ git push -u origin marcos/gitignore
```

Here are some resources that may be useful for learning a bit more about git:

https://onlywei.github.io/explain-git-with-d3/
https://learngitbranching.js.org/

**Comment by nahueespinosa** [comment]
Hey, let me know if you want to sync (google meet) for this

**Comment by marcosmarp** [comment]
> I don't think running git init on an already initialized repository is a great idea
My bad! When should i use git init? when i want to add a new repo?

> I'd suggest you delete your local copy of the repo (all relevant changes should already be on github) and create a new branch using this procedure
Will do that rn :)

> Hey, let me know if you want to sync (google meet) for this
Will let you know! I'll try to do it and if i can't a sync meeting would be great. Thanks!!
