### ISSUE TITLE
Usage of "using namespace std;"

### ISSUE THREAD

**Issue by nahueespinosa** [marcosmarp/signIn-signUp#4]
## Description
`using namespace std;` is considered bad practice because it could lead to unexpected conflicts and difficult to maintain code.
Remove those lines and replace the functions calls with the correponding namespace (i.e. `std::cout`). This also makes the code more readable.

## References
https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice

**Comment by marcosmarp** [comment]
Just merged #7! Closing the issue.
