### ISSUE TITLE
Changelog updates and releases

### ISSUE THREAD

**Issue by marcosmarp** [marcosmarp/signIn-signUp#9]
When should I update the changelog? Every time a new release is released? Is there a standard procedure for that?
And, when should i publish a new release? Every time i update the code? Thanks!

**Comment by nahueespinosa** [comment]
It depends on how the team is organized. The goal of a changelog is to communicate notable changes between releases for end users and developers. Usually a release comprises several features added in a given period of time. Releasing a new version every one or two commits may not be very practical.

For widely used software, the release cycle is usually well defined and support is provided only for the latest versions (or [LTS](https://en.wikipedia.org/wiki/Long-term_support) versions). So it plays a significant role in communicating with customers.

Depending on the development methodology adopted by the company, some teams are constantly deploying their changes to production (see [CI/CD](https://www.redhat.com/en/topics/devops/what-is-ci-cd)), so they can even automate the generation of a changelog based on the latest commits (usually is best to curate the results anyways).

**Comment by marcosmarp** [comment]
Thanks for the answer! 

It would be correct to update the changelog every time I merge a branch to the main one? And therefore, add new releases only when "big" functions are added to the program

**Comment by nahueespinosa** [comment]
Actually, for this project I wouldn't update the changelog on every PR. I think it's best to work without worrying too much about it for now.

**Comment by marcosmarp** [comment]
Got it! Closing the issue
